# Generated by Django 4.2.5 on 2023-09-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
